name: Node.js CI

on:
  push:
    branches: '**'
    tags-ignore: '**'
  pull_request:
    branches: '**'

jobs:

  lint:

    name: Lint Files

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: |
        npm install
        npm run lint

  test-eslint-8:

    name: test (Node.js ${{ matrix.node-version }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['12.22.0', '12', '14', '16']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm install eslint@8 eslint-plugin-cypress@2
        npm test

  test:

    name: Test (Node.js ${{ matrix.node-version }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.18.0', '18', '20', '21', '22']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm test
